let ErrorType = {
    TECHNICAL_ERROR: {id: 1, httpCode: 600, message : "There has been a general error, please try again later", isShowStackTrace: true},
    NO_CATEGORIES: {id: 2, httpCode: 606, message: "No categories were found in DB", isShowStackTrace: true},
    NO_CATEGORY_PRODUCTS: {id: 3, httpCode: 607, message: "No category products were found in DB", isShowStackTrace: true},
    INVALID_CATEGORY_ID: {id: 4, httpCode: 608, message: "Invalid category ID", isShowStackTrace: false},
    INVALID_SEARCH_VALUE: {id: 5, httpCode: 609, message: "Invalid search value", isShowStackTrace: false},
    USER_ALREADY_EXISTS: {id: 6, httpCode: 610, message: "User already exists", isShowStackTrace: false},
    MISSING_CUSTOMER_PARAMETERS: {id: 7, httpCode: 611, message: "One of the customer details is missing", isShowStackTrace: true},
    PASSWORDS_DONT_MATCH: {id: 8, httpCode: 612, message: "Customer's password and confirm password does not match", isShowStackTrace: false},
    INVALID_ID_NUMBER_PATTERN: {id: 9, httpCode: 613, message: "Customer's ID number format is invalid", isShowStackTrace: false},
    INVALID_EMAIL_ADDRESS_PATTERN: {id: 10, httpCode: 614, message: "Customer's email address format is invalid", isShowStackTrace: false},
    INVALID_PASSWORD_PATTERN: {id: 11, httpCode: 615, message: "Customer's password format is invalid", isShowStackTrace: false},
    INVALID_CONFIRM_PASSWORD_PATTERN: {id: 12, httpCode: 616, message: "Customer's confirm password format is invalid", isShowStackTrace: false},
    INVALID_FIRST_NAME_PATTERN: {id: 13, httpCode: 617, message: "Customer's first name format is invalid", isShowStackTrace: false},
    INVALID_LAST_NAME_PATTERN: {id: 14, httpCode: 618, message: "Customer's last name format is invalid", isShowStackTrace: false},
    INVALID_STREET_PATTERN: {id: 15, httpCode: 619, message: "Customer's street name format is invalid", isShowStackTrace: false},
    INVALID_CHOSEN_CITY_PATTERN: {id: 16, httpCode: 620, message: "Customer's city is invalid", isShowStackTrace: false},
    INVALID_CUSTOMER_CREDENTIALS: {id: 17, httpCode: 621, message: "One of the customer login credentials is incorrect - please try again", isShowStackTrace: false},
    INVALID_TOKEN: {id: 18, httpCode: 622, message: "Invalid token", isShowStackTrace: true},
    INVALID_PRODUCTS_COUNT: {id: 19, httpCode: 623, message: "No products were found in DB", isShowStackTrace: true},
    INVALID_ORDERS_COUNT: {id: 20, httpCode: 624, message: "No orders were found in DB", isShowStackTrace: true},
    MISSING_PRODUCT_DETAILS: {id: 21, httpCode: 625, message: "One of the product details is missing", isShowStackTrace: true},
    INVALID_PRODUCT_NAME: {id: 22, httpCode: 626, message: "Product name is invalid", isShowStackTrace: false},
    INVALID_PRODUCT_PRICE: {id: 23, httpCode: 627, message: "Product price format is invalid", isShowStackTrace: false},
    INVALID_PRODUCT_IMAGE: {id: 24, httpCode: 628, message: "Product image format is invalid", isShowStackTrace: false},
    INVALID_PRODUCT_CATEGORY: {id: 25, httpCode: 629, message: "Product category format is invalid", isShowStackTrace: false},
    INVALID_PRODUCT_ID: {id: 26, httpCode: 630, message: "Product id is invalid", isShowStackTrace: false},
    PRODUCT_ALREADY_EXIST: {id: 27, httpCode: 631, message: "Product already exists", isShowStackTrace: false},
    INVALID_CART_ID: {id: 28, httpCode: 632, message: "Invalid cart Id", isShowStackTrace: true},
    INVALID_ORDERS_SHIPMENTS_DATES: {id: 29, httpCode: 633, message: "No orders shipments dates were found in DB", isShowStackTrace: true},
    MISSING_ORDER_DETAILS: {id: 30, httpCode: 634, message: "One of the order details is missing", isShowStackTrace: true},
    INVALID_CREDIT_CARD_PATTERN: {id: 31, httpCode: 635, message: "Credit card pattern is invalid", isShowStackTrace: true},
    SHIPMENT_DATE_IS_FULL: {id: 32, httpCode: 636, message: "Selected shipment date is already full", isShowStackTrace: true}, 
}

module.exports = ErrorType;